version: '3'
services:
  zuul-gateway:
    build: zuul-gateway
    container_name: zuul_gateway
    ports:
      - "8886:8080" # map internal 8080 to external 9000
    environment:
      server.port=8080:
      eureka.client.serviceUrl.defaultZone=http://eureka-discovery-server:8761/eureka:
      zuul.routes.whiskeyapi=/whiskeyapi/**:
      zuul.routes.whiskeyauth=/whiskeyauth/**:
  mysql:
    build: docker/mysql
    container_name: whiskey_service_database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: TestPassw0rd
    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d
  eureka-discovery-server:
    build: docker/eureka
    container_name: eureka_discovery_service
    ports:
      - "8761:8761"
    environment:
      eureka.client.register-with-eureka=false:
      eureka.client.fetch-registry=false:
      eureka.server.renewal-percent-threshold=0.49:
  auth:
    build: whiskey-auth
    container_name: whiskey_service_auth
    ports:
      - "8887:8080" # map internal 8080 to external 8887
    environment:
      server.port=8080:
      spring.datasource.url=jdbc:mysql://mysql:3306/whiskey_api?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false:
      management.endpoints.web.exposure.include=refresh:
      eureka.client.serviceUrl.defaultZone=http://eureka-discovery-server:8761/eureka:
    depends_on:
      zuul-gateway:
        condition: service_started
      mysql:
        condition: service_started
      eureka-discovery-server:
        condition: service_started
      sleuth-zipkin:
        condition: service_healthy
  #    healthcheck:
  #      test: [ "CMD", "curl", "--fail", "http://localhost:8080/whiskeyapi/api/whiskeys"]
  #      interval: 10s
  #      timeout: 30s
  #      retries: 10
  api:
    build: whiskey-api
    container_name: whiskey_service_api
    ports:
      - "8888:8080" # map internal 8080 to external port 8888
    environment:
      server.port=8080:
      spring.datasource.url=jdbc:mysql://mysql:3306/whiskey_api?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false:
      security.oauth2.resource.user-info-uri=http://auth:8080/whiskeyauth/auth/user:
      management.endpoints.web.exposure.include=refresh:
      eureka.client.serviceUrl.defaultZone=http://eureka-discovery-server:8761/eureka:
    depends_on:
      zuul-gateway:
        condition: service_started
      mysql:
        condition: service_started
      auth:
        condition: service_started
      eureka-discovery-server:
        condition: service_started
      sleuth-zipkin:
        condition: service_healthy
#    healthcheck:
#      test: [ "CMD", "curl", "--fail", "http://localhost:8080/whiskeyapi/api/whiskeys"]
#      interval: 10s
#      timeout: 30s
#      retries: 10
  api-replica:
    build: whiskey-api
    container_name: whiskey_service_api_replica
    ports:
      - "8889:8080" # map internal 8081 to external port 8888
    environment:
      server.port=8081:
      spring.application.name=whiskey-service-api-replica:
      spring.datasource.url=jdbc:mysql://mysql:3306/whiskey_api?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false:
      security.oauth2.resource.user-info-uri=http://auth:8080/whiskeyauth/auth/user:
      management.endpoints.web.exposure.include=refresh:
      eureka.client.serviceUrl.defaultZone=http://eureka-discovery-server:8761/eureka:
    depends_on:
      zuul-gateway:
        condition: service_started
      mysql:
        condition: service_started
      auth:
        condition: service_started
      eureka-discovery-server:
        condition: service_started
      sleuth-zipkin:
        condition: service_healthy
#    healthcheck:
#      test: [ "CMD", "curl", "--fail", "http://localhost:8080/whiskeyapi/api/whiskeys"]
#      interval: 10s
#      timeout: 30s
#      retries: 10
  sleuth-zipkin:
    build: docker/zipkin
    container_name: sleuth_zipkin_server
    ports:
      - "9411:9411"
